### PR TITLE
Fix bc output (number starting with decimal point)

### LINKED ISSUE #3: Numbers beginning with decimal point can be generated (rarely)
Example: 
- Download https://bitmidi.com/uploads/48525.mid
- Run `mid2beep -c=2 -m=48525.mid`
- Resulting command begins with `beep -f 87.31 -l .98` which beep does not like.

This is caused by the `bc` command not outputting leading zeroes, e.g.
`$ bc -l <<< "0.98"`
`.98`

Can be easily fixed by formatting with awk, as per [this thread](https://stackoverflow.com/a/8402553):
`$ bc -l <<< "0.98" | awk '{printf "%f", $0}'`
`0.980000`

### PR DESCRIPTION
**Pull request by lawfulstupid**
Fixes #3

### CODE REVIEW

**Comment by lawfulstupid** [comment]
Also added usage information for `-b` flag while I was in there

**Comment by Cqoicebordel** [comment]
Awesome !
Thanks a lot ! And nice catch for the `-b` !

Just, before merging, I'm wondering if limiting the output of awk to 2 decimals would be better. As in replacing `awk '{printf "%f", $0}'` with `awk '{printf "%.2f", $0}'`.
Since there can be a loss of precision, I'm not 100% sure, even if it wouldn't be audibly different, I believe.

Anyway, if you agree to the limit, I let you add that change. If not, tell me, and I'll merge as is :)

**Comment by lawfulstupid** [comment]
Good thinking. I've used the compute function in a few places: frequency, speed factor, delay, and note length. The first two are already truncated to 2dp by the expressions beginning `LANG=` on their respective next lines. The second two are measured in ms, and I don't think anyone is going to notice a sub-centimillisecond (i.e. nanosecond) difference in timing, so I've made a change to the compute function to always truncate to 2dp.

One thing I don't understand in the source code is
`LANG=${langdef}`
`LC_NUMERIC=${numericdef}`

Do you think we'll need this in the compute function to make sure the numbers are formatted correctly? If not, the `langdef` and `nunericdef` vars could be removed.

**Comment by Cqoicebordel** [comment]
I'm fuzzy on the `LANG` part too, but I believe it's necessary for printf : it's there if the OS used doesn't have those variables set (see #2). And since we still use printf in awk, I _think_ it's still useful. Might also be useful for locales which uses non-latin chars for numerics.

So, in fact, I'm wondering if it should be included in the compute one-liner. I believe so, but could be wrong.

**Comment by lawfulstupid** [comment]
Alrighty, I've done some research on the topic. `LANG` and `LC_NUMERIC` are used by `printf` to determine how to format numbers, e.g. some locales use commas instead of a decimal point. We, however, want to always use an English locale for our number formatting because that's what works with `beep`. So yes we should set these variables in the `compute` function. I've used `POSIX` for both (which `C` is an alias for) as it's guarantee to be installed on all systems and produces numbers in the format we want -- previously en_US was used but that might not be installed. Unlikely, but possible.

**Comment by lawfulstupid** [comment]
Also in the spirit of maximum compatibility: I've swapped the AWK `printf` for a plain old bash `printf`. There might be someone out there who doesn't have AWK installed, you never know.

**Comment by Cqoicebordel** [comment]
Thank you.
Really, thank you for going above and beyond to make this silly project still work _the right way_.

I'm always flabbergasted that anybody would use this at all, so seeing you propose changes and take into account my comments and go even beyond to make it better really warms my heart :) 

So yeah, ok to merge, obviously, and thanks again :)

**Comment by lawfulstupid** [comment]
My pleasure, I just really like making my computer beep to the tune of Africa by Toto :)
Thanks for making this project!

**Pull request merged**
